djangoapp/blog/urls.py
# flake8: noqa

from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post'),
    path('page/<slug:slug>/', views.PageDetailView.as_view(), name='page'),
    path('created_by/<int:_id>/',views.CreatedByListView.as_view(), name='created_by'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
    path('tag/<slug:slug>/', views.TagListView.as_view(), name='tag'),
    path('search/', views.SearchListView.as_view(), name='search'),
]

djangoapp/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/blog/models.py
from django.db import models
from utils.rands import slugify_new
from django.contrib.auth.models import User
from utils.images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse


class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by('-id')


class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name == self.file.name

        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name

        if file_changed:
            resize_image(self.file, 900, optimize=True, quality=70)

        return super_save


class Tags(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True, max_length=100, default=None, null=True, blank=True
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, max_length=200, default=None, null=True, blank=True
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Page(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True, max_length=200, default=None, null=True, blank=True
    )
    is_published = models.BooleanField(
        default=True,
        help_text='Marque essa opção para exibir a página.'
    )
    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')

        return reverse('blog:page', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    objects = PostManager()

    title = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True, default='', null=False, blank=True, max_length=255
    )
    exerpt = models.CharField(max_length=100)
    is_published = models.BooleanField(
        default=False,
        help_text='Marque essa opção para exibir a página.'
    )
    content = models.TextField()
    cover = models.ImageField(
        upload_to='posts/%Y/%m', blank=True, default=''
    )
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text='Exibe a imagem de capa dentro do conteúdo do post'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='post_created_by',
    )
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='post_updated_by',
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL,
        null=True, blank=True, default=None
    )
    tags = models.ManyToManyField(Tags, blank=True, default='')

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')

        return reverse('blog:post', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title)

        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != self.cover.name

        if cover_changed:
            resize_image(self.cover, 900, optimize=True, quality=70)

        return super_save

djangoapp/blog/views.py
from django.shortcuts import redirect
from blog.models import Post, Page
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import Http404
from django.views.generic import ListView, DeleteView

PER_PAGE = 6


class PostListView(ListView):
    template_name = 'blog/pages/index.html'
    queryset = Post.objects.get_published()
    paginate_by = PER_PAGE
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Home -'
        return context


class CreatedByListView(PostListView):
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self._temp_context = {}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = self._temp_context['user']
        user_full_name = user.username

        if user.first_name:
            user_full_name = f'{user.first_name} {user.last_name}'
        page_title = 'Posts de ' + user_full_name + ' - '

        ctx.update({
            'page_title': page_title,
        })

        return ctx

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(created_by__pk=self._temp_context['user'].pk)
        return qs

    def get(self, request, *args, **kwargs):
        _id = self.kwargs.get('_id')
        user = User.objects.filter(pk=_id).first()

        if user is None:
            raise Http404

        self._temp_context.update({
            '_id': _id,
            'user': user,
        })

        return super().get(request, *args, **kwargs)


class CategoryListView(PostListView):
    allow_empty = False

    def get_queryset(self):
        return super().get_queryset().filter(
            category__slug=self.kwargs['slug']
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page_title'] = f'{self.object_list[0].category.name} - Categoria'
        return ctx


class TagListView(PostListView):
    allow_empty = False

    def get_queryset(self):
        return super().get_queryset().filter(
            tags__slug=self.kwargs['slug']
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page_title'] = f'{self.object_list[0].tags.first().name} - Tag -'
        return ctx


class SearchListView(PostListView):
    def __init__(self, *agrs, **kwargs) -> None:
        super().__init__(*agrs, **kwargs)
        self._search_value = ''

    def setup(self, request, *args, **kwargs) -> None:
        self._search_value = request.GET.get('search').strip()
        return super().setup(request, *args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset().filter(
            Q(title__icontains=self._search_value) |
            Q(exerpt__icontains=self._search_value) |
            Q(content__icontains=self._search_value)
        )[0:PER_PAGE]
        return qs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        ctx['page_title'] = f'{self._search_value[:20]} - Search -'
        ctx['search_value'] = self._search_value
        return ctx

    def get(self, request, *args, **kwargs):
        if self._search_value == '':
            return redirect('blog:index')
        return super().get(request, *args, **kwargs)


class PageDetailView(DeleteView):
    model = Page
    template_name = 'blog/pages/page.html'
    slug_field = 'slug'
    context_object_name = 'page'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        print(ctx)
        single_page = self.get_object()
        ctx['page_title'] = f'{single_page.title} - Página -'
        return ctx

    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class PostDetailView(DeleteView):
    model = Post
    template_name = 'blog/pages/post.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        single_post = self.get_object()
        ctx['page_title'] = f'{single_post.title} - Post -'
        return ctx

    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)

djangoapp/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        {% if posts %}
        <div class="card-grid">
          {% for post in posts %}
            {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
          {% endfor %}
        </div>
        {% else %}
          <div class="not-found center">
            <h1>Nada encontrado</h1>
            <p>Não encontrei nada nesse link, por favor clique em outro link ou vá para a <a href="{% url "blog:index" %}">Home</a></p>
          </div>
        {% endif %}
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center"> {{ page.title }} </h1>
          {{ page.content | safe}}
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %}
      <div class="single-post-cover pb-base">
        <img loading="lazy" src="{{ post.cover.url }}" alt=" {{ post.title}}">
      </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{ post.title }}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url 'blog:created_by' post.created_by.pk %}">
            <i class="fa-solid fa-user"></i>
            <span>
              {% if post.created_by.first_name %}
                {{ post.created_by.first_name}}
                {{ post.created_by.last_name}}
              {% else %}
                {{ post.created_by.username }}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{ post.created_at | date:'d/m/Y' }}
            </span>
          </span>
        </div>

        {% if post.category %}
          <div class="post-meta-item">
            <a class="post-meta-link" href="{% url "blog:category" post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span>
                {{ post.category.name}}
              </span>
            </a>
          </div>
        </div>
      {% endif %}

      <p class="single-post-excerpt pb-base">
        {{ post.exerpt | safe}}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{ post.content | safe }}
      
        <div class="post-tags">
          <span>Tags: </span>
          
          {% if post.tags.exists %}
            {% for tag in post.tags.all %}
            <a class="post-tag-link" href="{% url "blog:tag" tag.slug %}">
              <i class="fa-solid fa-link"></i>
              <span>{{tag.name}}</span>
            </a>
            {% endfor %}
          {% else %}
            <p>post sem tags</p>
          {% endif %}
        </div>
        
      </div>
    
    </div>
  </div>
</main>

{% endblock content %}